FROM registry.access.redhat.com/ubi8
RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y \
    && dnf update \
    && dnf install sudo htop nload vnstat curl wget -y \
    && dnf clean all \
  	&& rm -rf /var/cache/yum
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]




# RUN sudo echo "root:123" | sudo chpasswd